name = "exam-site"
pages_build_output_dir = "dist"

[[ d1_databases ]]
binding = "DB"
database_name = "exam-db"
database_id = "987b11a1-b4da-454a-9bbf-5354dcc1eceb"

[vars]
ADMIN_PASSWORD = "changeme"
